### PR TITLE
Update/2020 mtsdk

### PR DESCRIPTION
**Pull request by MCFurry**
Testing the MTi-680G I got the new version of the mt sdk.
This also included an updated ROS driver.
Looks like mostly comments changed and some minor improvements with thread locks etc.

### CODE REVIEW

**Comment by Timple** [comment]
Poeh, does it work?

Lets try both xsense versions we have and then merge

**Comment by MCFurry** [comment]
I've tested this new version this morning with the MTi-680G and seems to work flawlessly.
Unfortunately there's a lot of diff because of all the changed headers. I don't think there is too much change functional wise, probably more robust if I look at them.
But let's try on Harvey one day!

**Review by Timple — APPROVED** [review]

**Comment by Timple** [comment]
For Noetic a Compile error has been fixed in MT Software Suite release, version 2020.0.2.

Would you mind providing a PR for that as well?

**Comment by MCFurry** [comment]
I'll have a look!

**Pull request merged**
